name: Jason Hepburn
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
paginate: 5
paginate_path: "/blog/page:num/"
plugins:
  - jekyll-sitemap

twitter_username:     jj_hepboin
github_username:      attler
linkedin_username:    jason-hepburn-b585701a
google_plus_username:
facebook_username:    CautionAI
dribbble_username:
google_scholar_username: GsjbRuAAAAAJ
